### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by gokulan97** [ShaastraWebops/CA-Site-2018#16]
Add forgot password option in the login page.

Almost the same as main website. If needed, create a new route(Frontend route -- url) for forgot password if needed.

The sendgrid API key has been updated in the sheet which was shared earlier.

Push to MASTER.

**Comment by kaarthik-raja** [comment]
i hope the website address in the password change is correct (ca.shaastra.org/resetpassword/email/token), otherwise working properly
To test the code in localhost , take the mail and token part (that came to you in mail ) and put in the url bar as localhost:3001/resetpassword/email/token ...
